- docs/index.html
**Resolves Issue:** #16 
- Set basePath to upstream master
> Set basePath to upstream master

- docs/_sidebar.md
- docs/events/hosting.md
- docs/grading/appeal_policies.md
- docs/grading/flex.md
- docs/mentoring/training.md
- docs/overview/contact.md
- docs/overview/projects.md
- docs/resources/brand_standards.md
**Resolves Issue:** (add GitHub issue number here)
- Added links in grading/flex.md
- Added links to RCOS-sponsored GitHub projects
- Added events/hosting.md
- Updated Sidebar
- Added placeholder file for grade appeals
> Updates & Placeholder Pages

- docs/_sidebar.md
- docs/coordinating/README.md
- docs/membership/requirements.md
- docs/overview/history.md
See commit messages for breakdown of changes
> Added membership requirements, history

- docs/_coverpage.md
- docs/resources/brand_assets.md
**Resolves Issue:** Filename changes in `rcos-branding`
> Replaced images to latest assets

- docs/_sidebar.md
- docs/coordinating/observatory.md
- docs/coordinating/passwords.md
- docs/membership/join_rcos.md
- docs/overview/history.md
- docs/overview/projects.md
- Added RCOS history from GDrive presentation 
- Added coordinator documentation for Observatory, passwords
> History & Coordinator Docs

- docs/membership/join_rcos.md
- docs/membership/speed_dating.md
- docs/resources/brand_standards.md
- docs/resources/slides.md
**Resolves Issue:** #43 
- Corrected Pantone 424 color in brand standards (issue #43)
- Partial resolution of #11 (Add Speed Dating documentation)
- Added link to intro slides hosted on GitPitch.com
> Speed dating documentation & slides

- docs/_sidebar.md
- docs/coordinating/faculty.md
- docs/grading/documentation.md
- docs/membership/join_rcos.md
- docs/membership/new_projects.md
- docs/membership/requirements.md
- docs/resources/CODE_OF_CONDUCT.md
- docs/resources/code_of_conduct_template.md
**Resolves Issue:** #25 
- Flesh out "what you'll need"
- Add a guide for new projects
- Rename anti harassment guidelines to "definition of harassment" (avoids making CoC seem longer than it actually is)
- Add starter page for faculty advisors
- Add documentation guidelines
> Newbie guide

- docs/index.html
- Improved Docsify search functionality in sidebar.
> Improved Docsify search configuration

- docs/overview/history.md
- docs/overview/sponsors.md
**Partially resolves Issue:** #45
> Sponsor links and descriptions

- docs/grading/status_updates.md
- Cleaned up Status Updates documentation to align with [rcos/rcos-status-updates](https://github.com/rcos/rcos-status-updates)
> Refined Status Updates documentation

- docs/mentoring/replacement.md
**Resolves Issue:** (add GitHub issue number here)
-
-
-
> add mentor/coordinator replacement info

- docs/events/hosting.md
- docs/grading/appeal_policies.md
**Resolves Issue:** (add GitHub issue number here) #19, #30
- add appeal details
- add event hosting details
TODO: @aeksco create PDF so I can link that
> Fix #19, #30

- docs/grading/attendance.md
**Resolves Issue:** #68
- add deadline for excused absence
> resolve issue #68

- docs/_sidebar.md
- docs/work_groups/README.md
- docs/work_groups/inventory.md
- docs/work_groups/student_resources.md
**Resolves Issue:**N/A
- Merged the `Inventory` work group tasks into the `Student Resources` work group
> Merged inventory & student resources work groups

- docs/grading/appeal_policies.md
**Resolves Issue:** #72 
- Added link to `appeal_policies`
> Added link to Fall 2018 grade appeal form to grading/appeal_policies.md

- docs/coordinating/agenda.md
- docs/grading/README.md
**Resolves Issue:** #61 
-
-
-
> Resolve issue #61

- docs/grading/rubric.md
I did not require a individual end-of-year write up. We can
discuss that before kick-off. I believe everything else is
reasonably covered.
**Resolves Issue:** (add GitHub issue number here)
-
-
-
> Issues 40 and 93

- docs/grading/finalpresentionguideline.md
This is in response to issue #117.
**Resolves Issue:** #117 
**Changes in this pull request**: New file
-
-
-
> Add guidelines for the final presentation

- README.md
- docs/_sidebar.md
- docs/grading/flex.md
**Resolves Issue:** #121 
- Removes `Work Groups` section from sidebar until we have a chance to reevaluate its inclusion.
- Bumps version to `0.2.1`
> Commented out notes regarding Work Groups

- docs/mentoring/README.md
- docs/mentoring/training.md
- remove incorrect mentor information
- add note about remote learning
> Mentors Update

- docs/_coverpage.md
- docs/_sidebar.md
- docs/meetings/large_group_meetings.md
- docs/meetings/small_group_meetings.md
- docs/membership/project_pairing.md
**Resolves Issue:** (add GitHub issue number here)
- Temporarily comment out large and small group meeting formats
- Document large and small group online formats
> Online Meetings

- docs/grading/README.md
> Add notice about non-credit members

- docs/project_management/new_projects.md
- docs/project_management/pitch.md
Fleshed out the documentation for projects, mainly for new project leads.
> More Detailed Documentation

- docs/meetings/large_group_meetings.md
Specifies a 40 minute time limit for guest speakers.
Closes #84
> Add a time limit for guest speakers.

- docs/coordinating/agenda.md
- docs/meetings/inclement_weather.md
- docs/meetings/large_group_meetings.md
- docs/meetings/small_group_meetings.md
- docs/membership/project_pairing.md
- docs/mentoring/README.md
> Return to In-Person

- docs/mentoring/README.md
- explicitly require mentors to meet once a week with their small groups
- fixed some first/second/third person stuff for clarity (and perhaps my own peace of grammatical mind)
> update small group meeting policy

- docs/resources/README.md
Closes #174 
A complete overhaul of the student resources page. More links, more sections, and more descriptions. There is also a table of contents to help navigate it all. I tried my best to keep it as free and open source as possible and I may have went over board with the frameworks and programming languages.
To the reviewer, make sure the descriptions are correct for the most part. I tried to keep it as consistent as possible but I may have made spelling mistakes or put slightly incorrect information. Feel free to add more, remove some, and whatever you feel is best!
> Updated Student Resources Page

- docs/_sidebar.md
- docs/overview/one_page.md
This is a one page **unofficial** syllabus for the RCOS handbook that allows students to easily access on critical RCOS information. This information includes: What RCOS is, list of current faculty and coordinators (along with contact information), grading for students, grading for mentors, Semester outline, learning outcome, academic policies, and other relevant course information.
> RCOS One Page Syllabus

- docs/grading/status_updates.md
Added more description to the status update page in the handbook. These changes include: A brief grading breakdown of each section of a status update, descriptions of what we want and don't want for each section, and adding more detail to the example one to better reflect what's expected.
> Status-Update Page Update

- docs/README.md
- docs/meetings/inclement_weather.md
- docs/meetings/large_group_meetings.md
- docs/meetings/semester_outline.md
- docs/meetings/small_group_meetings.md
- docs/membership/join_rcos.md
- docs/membership/project_pairing.md
- docs/membership/requirements.md
- docs/overview/contact.md
- docs/overview/faq.md
- docs/overview/history.md
I made some QOL changes to the Overview, Getting Started, and Meetings section of the handbook. The changes are mainly updating deadlinks, spell checking, using modern markdown conventions, deleting old/irrelevant sections, and adding more information to places with sparce descriptions. If you notice an error or have a gripe with anything I may have changed feel free to leave a comment and I'll gladly update it.
> Handbook Update - Overview, Getting Started and Meetings

- docs/grading/attendance.md
We have changed our attendance policy in light of the new instructor attendance policy to give students more flexibility. We should change the handbook to reflect this.
> Update attendance policy

- docs/_coverpage.md
- docs/overview/one_page.md
Small changes to handbook dates and coordinator/faculty information for the spring 2025 semester.
> Spring 25 Update
